INSERT INTO tb_user (name, email, password) VALUES ('Alex Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown',  'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Aventura');

INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('The Walking Dead', 'Lute contra os mortos. Tema os vivos', 2010, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/xVzvD5BPAU4HpleFSo8QOdHkndo.jpg', 'Nos Estados Unidos pós-apocalíptico, um pequeno grupo de sobreviventes segue viajando à procura de uma nova casa longe dos mortos-vivos. O desespero por segurança e suprimentos os coloca constantemente à beira da sanidade', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('John Wick De Volta ao Jogo', 'Agora é pessoal', 2014, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/7dzngS8pLkGJpyeskCFcjPO9qLF.jpg', 'John Wick é um lendário assassino de aluguel aposentado, lidando com o luto após perder o grande amor de sua vida. Quando um gângster invade sua casa, mata seu cachorro e rouba seu carro, ele é forçado a voltar à ativa e inicia sua vingança', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('Homem-Aranha', 'Com grandes poderes vem grandes responsabilidades.', 2002, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/sWvxBXNtCOaGdtpKNLiOqmwb10N.jpg', 'Peter Parker é um jovem estudioso que vive com seus tios, Ben e May, desde que seus pais faleceram. Peter tem dificuldade em se relacionar com seus colegas, por ser tímido e por eles o considerarem um nerd. Até que, em uma demonstração científica, um acidente inesperado faz com que aranha modificada geneticamente pique Peter. A partir de então seu corpo é quimicamente alterado pela picada da aranha.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('O Diabo de Cada Dia', 'Todos acabam no mesmo lugar maldito.', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/rUeqBuNDR9zN6vZV9kpEFMtQm0E.jpg', 'Em um lugar tomado por corrupção e violência, um jovem enfrenta figuras sinistras para proteger quem mais ama.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('O Resgate do Soldado Ryan', 'A missão é um homem.', 1998, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/hjQp148VjWF4KjzhsD90OCMr11h.jpg', 'Ao desembarcar na Normandia, no dia 6 de junho de 1944, capitão Miller (Tom Hanks) recebe a missão de comandar um grupo do segundo batalhão para o resgate do soldado James Ryan, caçula de quatro irmãos, dentre os quais três morreram em combate. Por ordens do chefe George C. Marshall, eles precisam procurar o soldado e garantir o seu retorno, com vida, para casa.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('Coringa', 'Coloque um sorriso nessa cara.', 2019, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg', 'Arthur Fleck trabalha como palhaço para uma agência de talentos e, toda semana, precisa comparecer a uma agente social, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage mal à gozação de três homens em pleno metrô e os mata. Os assassinatos iniciam um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('Corações de Ferro', 'Uma guerra nunca termina serenamente.', 2014, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/1uKHoFWyYJn060dpIXUCU7Wbc15.jpg', 'Durante o final da Segunda Guerra Mundial, um grupo de cinco soldados americanos é encarregado de atacar os nazistas dentro da própria Alemanha. Apesar de estarem em quantidade inferior e terem poucas armas, eles são liderados pelo enfurecido Wardaddy (Brad Pitt), sargento que pretende levá-los à vitória, enquanto ensina o novato Norman (Logan Lerman) a lutar.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('Mad Max: Estrada da Fúria', 'Só os loucos sobrevivem.', 2015, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/nlCHUWjY9XWbuEUQauCBgnY8ymF.jpg', 'Em um mundo apocalíptico, Max Rockatansky acredita que a melhor forma de sobreviver é não depender de ninguém. Porém, após ser capturado pelo tirano Immortan Joe e seus rebeldes, Max se vê no meio de uma guerra mortal, iniciada pela imperatriz Furiosa que tenta salvar um grupo de garotas. Também tentando fugir, Max aceita ajudar Furiosa. Dessa vez, o tirano Joe está ainda mais implacável pois teve algo insubstituível roubado.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('Coraline e o Mundo Secreto ', 'Cuidado com o que deseja...', 2009, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/p5ixxu4V6VYBvr26xBKsaPrElu6.jpg', 'Entediada em sua nova casa, a pequena Coraline descobre uma porta secreta que contém um mundo parecido com o dela, porém melhor em muitas maneiras. Coraline se encanta com a descoberta, mas logo descobre que há algo de errado quando seus pais alternativos tentam mantê-la eternamente nesse mundo paralelo.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES	('Um Olhar do Paraíso', 'The story of a life and everything that came after...', 2009, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/A9HuORNvHQq7Rf8Jm4MyUvwBHlP.jpg', 'Susie Salmon está voltando para casa quando é assassinada por George Harvey, um vizinho que mora sozinho. Os pais de Susie, Jack e Abigail, inicialmente se recusam a acreditar na morte da filha. Em meio às investigações, a polícia conversa com George mas não o coloca entre os suspeitos, mas a família passa a desconfiar dele. Susie, que agora está em um local entre o paraíso e o inferno, observa a situação e lida com o sentimento de vingança e a vontade de ajudar sua família a superar sua morte.', 3);

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Um drama de terror seguindo os sobreviventes de um holocausto apocalíptico que está procurando por um refúgio seguro enquanto é perseguido e ameaçado por zumbis. Adaptado de uma série de quadrinhos.', 2, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('O ex-assassino John Wick, deixa sua antiga vida devido a uma paixão que encontrou em sua vida. logo apos perder o amor da sua vida, ele sofre um ataque que desencadeia a volta dele pro jogo. filme top',3, 2);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Este filme mostra, basicamente, o surgimento do Homem Aranha: a forma como Peter Parker, um adolescente, muda de vida após ter sido picado por uma aranha geneticamente modificada. Ele torna-se um herói, capaz de fazer justiça e proteger os mais fracos. Porém, do outro lado da barricada, surge o Duende Verde, um vilão que só ele pode travar.', 1, 3);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('O diabo de cada dia é um filme bom, relata de como temos que enfrentar nossas batalhas internas e encarar o diabo na nossa rotina monotona. Mostra também como devemos ficar atento as pequenas coisas, pois o diabo mora nos detalhes', 3, 4);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Filme bem realista, que mostra como é viver em uma guerra e como é sofrer perdas, e mesmo ter que continuar em frente', 1, 5);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Um filme impactante. Ao mesmo nível de Clube de Luta! No qual a classe não tão afortunada se revolta com contra a classe opressora. Interessante notar a luta de classe.', 2, 6);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Relata como grandes homens com corações de ferro, conseguem fazer a diferença com força e determinação sem temer as consequencias', 3,7);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Filme que se passa em um deserto, em constante brigar por agua, com seguimento de carnificina e muita adrenalina', 1,8);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Uma animação que demonstra como devemos tomar cuidado com o que queremos, muitas das vezes nem tudo que desejamos, pode ser algo bom', 2, 9);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Achei bem triste e pesado relata a nossa realidade, onde acontece muitas coisas ruins, se não vemos a tempo', 1,10);

